-- Generated by nwg-displays on 2026-06-25 at 17:21:01. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "preferred",
    position = "0x0",
    scale = 1.0,
    mirror = "HDMI-A-1"
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "preferred",
    position = "1920x0",
    scale = 1.0
})
