font_family JetBrainsMono Nerd Font
font_size 12
shell /usr/bin/zsh
#background_image /home/koios/Pictures/wallpapers/YoRHa_bg2.jpg
#background_image_layout cscaled
background_tint 0.85
background_opacity 0.4
